{{ if .Values.podScanner.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod-scanner
  labels:
    app: pod-scanner
spec:
  selector:
    matchLabels:
      app: pod-scanner
  template:
    metadata:
      labels:
        app: pod-scanner
    spec:
      containers:
      - name: pod-scanner
        image: {{ .Values.podScanner.image.repository }}:{{ .Values.podScanner.image.tag }}
        imagePullPolicy: {{ .Values.podScanner.image.pullPolicy }}
        env:
        - name: CONTAINER_MANAGER
          value: {{ .Values.podScanner.scannerIntegration.containerManager }}
        - name: POTENTIAL_DOCKER_SOCKET_LOCATIONS
          value: {{ .Values.podScanner.scannerIntegration.potentialDockerSocketLocations }}
        - name: POTENTIAL_CONTAINERD_NAMESPACES
          value: {{ .Values.podScanner.scannerIntegration.potentialContainerDNamespaces }}
        - name: POTENTIAL_CONTAINERD_SOCKET_LOCATIONS
          value: {{ .Values.podScanner.scannerIntegration.potentialContainerDSocketLocations }}
        - name: POTENTIAL_CONTAINERD_RUNTIME_TASK_LOCATIONS
          value: {{ .Values.podScanner.scannerIntegration.potentialContainerDRuntimeTaskLocations }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName        
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: hostvar
          mountPath: /host/var
          readOnly: true
        - name: hostrun
          mountPath: /host/run
          readOnly: true
        - name: hostmounts
          mountPath: /host/mounts
          readOnly: true
      volumes:
      - name: hostvar
        hostPath:
          path: /var
          type: Directory
      - name: hostrun
        hostPath:
          path: /run
          type: Directory
      - name: hostmounts
        hostPath:
          path: /proc/mounts
          type: File
{{end}}
